version: "2"

linters:
  enable:
    - nolintlint
  disable:
   # The following linters are disabled purely because this config was migrated to v2 where they are in the default
   # set, and we should have separate work to enable them if we truly want them.
   - staticcheck
   - errcheck
  exclusions:
    paths:
      - third-party

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
