name: Lint
on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - ".github/licenses.tmpl"
      - "script/licenses*"
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - ".github/licenses.tmpl"
      - "script/licenses*"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Verify dependencies
        run: |
          go mod verify
          go mod download

          LINT_VERSION=1.63.4
          curl -fsSL https://github.com/golangci/golangci-lint/releases/download/v${LINT_VERSION}/golangci-lint-${LINT_VERSION}-linux-amd64.tar.gz | \
            tar xz --strip-components 1 --wildcards \*/golangci-lint
          mkdir -p bin && mv golangci-lint bin/

      - name: Run checks
        run: |
          STATUS=0
          assert-nothing-changed() {
            local diff
            "$@" >/dev/null || return 1
            if ! diff="$(git diff -U1 --color --exit-code)"; then
              printf '\e[31mError: running `\e[1m%s\e[22m` results in modifications that you must check into version control:\e[0m\n%s\n\n' "$*" "$diff" >&2
              git checkout -- .
              STATUS=1
            fi
          }

          assert-nothing-changed go fmt ./...
          assert-nothing-changed go mod tidy

          bin/golangci-lint run --out-format=colored-line-number --timeout=3m || STATUS=$?

          exit $STATUS

      # actions/setup-go does not setup the installed toolchain to be preferred over the system install,
      # which causes go-licenses to raise "Package ... does not have module info" errors.
      # for more information, https://github.com/google/go-licenses/issues/244#issuecomment-1885098633
      - name: Check licenses
        run: |
          export GOROOT=$(go env GOROOT)
          export PATH=${GOROOT}/bin:$PATH
          ./script/licenses-check
