name: Notify on Deploy Status

on:
  workflow_run:
    workflows:
      - "Manual Deploy Setup"
      - "Auto Deploy to Server"
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check workflow status
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo "⚠️ Deployment failed!"
          echo "Workflow: ${{ github.event.workflow_run.name }}"
          echo "Run URL: ${{ github.event.workflow_run.html_url }}"
          echo "Status: ${{ github.event.workflow_run.conclusion }}"

      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USER }}
          password: ${{ secrets.MAIL_PASS }}
          subject: >
            ${{ github.event.workflow_run.name }} —
            ${{ github.event.workflow_run.conclusion == 'success' && '✅ Success' || '❌ Failed' }}
          to: ${{ secrets.NOTIFY_EMAIL }}
          from: "Nursery System CI"
          secure: true
          body: |
            Workflow: ${{ github.event.workflow_run.name }}
            Repository: ${{ github.repository }}
            Status: ${{ github.event.workflow_run.conclusion }}
            Run URL: ${{ github.event.workflow_run.html_url }}
            Triggered by: ${{ github.actor }}
            Commit: ${{ github.event.workflow_run.head_sha }}
