name: Marks/closes stale issues
on:
  schedule:
    - cron: "0 3 * * *" # 3 AM UTC

permissions:
  issues: write

jobs:
  mark-stale-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          start-date: "2025-07-10T00:00:00Z"  # Skip for issues created before this date
          days-before-issue-stale: 30
          only-issue-labels: 
            "needs-triage,needs-user-input"   # Only issues with all of these labels can be marked as stale
          exempt-issue-labels: "keep"         # Issues marked with this label should not be marked as stale
          stale-issue-label: "stale"          # Mark stale issues with this label
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had any activity in the last 30 days,
            and it will be closed in 30 days if no further activity occurs.

            If you think this is a mistake, please comment on this issue to keep it open.

          days-before-issue-close: 30
          close-issue-reason: "not_planned"
          close-issue-message: |
            This issue has been automatically closed due to inactivity.

            If you think this is a mistake, please comment on this issue.

          # Exclude PRs from closing or being marked as stale
          days-before-pr-stale: -1
          days-before-pr-close: -1
